name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Zip Scripts
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: scripts.zip
          exclusions: "*.git* README.*"
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: scripts.zip
          allowUpdates: true
          tag: v1.0.0
          
