name: Release

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Get tag
        id: get_tag
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Zip Scripts
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: scripts.zip
          exclusions: "*.git* README.*"

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: scripts.zip
          allowUpdates: true
          makeLatest: false
          tag: ${{ steps.get_tag.outputs.tag }}
          
